cc_library(
    name = "graph",
    hdrs = ["graph.h"],
    copts = ["-Iinclude"],
    includes = ["."],
    visibility = ["//test:__pkg__"],
)

cc_library(
    name = "circular_list",
    hdrs = ["circular_list.h"],
    copts = ["-Iinclude"],
    includes = ["."],
    visibility = ["//test:__pkg__"],
)

cc_library(
    name = "fibheap",
    hdrs = ["fibheap.h"],
    copts = ["-Iinclude"],
    includes = ["."],
    visibility = ["//test:__pkg__"],
)
